server:
  address: localhost
  servlet:
    path: /

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Sun1366560
    url: jdbc:mysql://localhost:3306/srs_player?characterEncoding=utf8&useSSL=false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
srs:
  allow:
   - stream1
   - stream2
   - stream3
   - stream4
   - stream5
   - stream6